version: '3.8'

services:
  app:
    image: portus-repo.co.ihc.com/devops/bb-gh-sync:latest # Replace with your image name and tag
    ports:
      - "3000:3000" # Map the container's port 3000 to your VM's port 3000
    environment:
      - NODE_ENV=production
      - GITHUB_USER=${GITHUB_USER}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - BITBUCKET_REPO_URL=${BITBUCKET_REPO_URL}
      - GITHUB_REPO_URL=${GITHUB_REPO_URL}
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
